/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PWM_A.h>
#include <Clock_1.h>
#include <BHI.h>
#include <BHI_aliases.h>
#include <BLI.h>
#include <BLI_aliases.h>
#include <motor_dis.h>
#include <motor_dis_aliases.h>
#include <ALI.h>
#include <ALI_aliases.h>
#include <AHI.h>
#include <AHI_aliases.h>
#include <QuadDec_1.h>
#include <Clock_3.h>
#include <B.h>
#include <B_aliases.h>
#include <A.h>
#include <A_aliases.h>
#include <UART_1.h>
#include <isr_2.h>
#include <Clock_4.h>
#include <LIN_1.h>
#include <QuadDec_1_Cnt16.h>
#include <UART_1_IntClock.h>
#include <LIN_1_UART.h>
#include <LIN_1_IntClk.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

